import Testing
@testable import WordCore

/// Port of `src/game/__tests__/modes.test.ts`, plus a golden-fixture parity
/// suite against `Fixtures/modes.json` (generated by tools/gen-fixtures.ts).

@Suite("Modes: endlessInitialSeconds") struct ModesEndlessInitialSeconds {
    @Test("gives regular two minutes and fast one")
    func givesRegularTwoMinutesAndFastOne() {
        #expect(endlessInitialSeconds(.regular) == ENDLESS_INITIAL_SECONDS)
        #expect(endlessInitialSeconds(.regular) == 120)
        #expect(endlessInitialSeconds(.fast) == FAST_INITIAL_SECONDS)
        #expect(endlessInitialSeconds(.fast) == 60)
    }
}

@Suite("Modes: endlessDripSeconds, regular") struct ModesEndlessDripSecondsRegular {
    @Test("holds 45 seconds for the first five rounds")
    func holds45SecondsForTheFirstFiveRounds() {
        for i in 0..<ENDLESS_SLOW_ROUNDS {
            #expect(endlessDripSeconds(i, .regular) == 45)
        }
    }

    @Test("tightens to 30 seconds forever after")
    func tightensTo30SecondsForeverAfter() {
        #expect(endlessDripSeconds(ENDLESS_SLOW_ROUNDS, .regular) == 30)
        #expect(endlessDripSeconds(10, .regular) == 30)
        #expect(endlessDripSeconds(100, .regular) == 30)
    }

    @Test("only ever gets shorter")
    func onlyEverGetsShorter() {
        for i in 1...30 {
            #expect(endlessDripSeconds(i, .regular) <= endlessDripSeconds(i - 1, .regular))
        }
    }
}

@Suite("Modes: endlessDripTiles, regular") struct ModesEndlessDripTilesRegular {
    @Test("deals fives through the slow rounds and the first fast ones")
    func dealsFivesThroughTheSlowRoundsAndTheFirstFastOnes() {
        for i in 0..<ENDLESS_SMALL_BATCH_ROUNDS {
            #expect(endlessDripTiles(i, .regular) == ENDLESS_SMALL_BATCH)
        }
    }

    @Test("keeps dealing fives when the clock first tightens")
    func keepsDealingFivesWhenTheClockFirstTightens() {
        // The 30-second rounds start at interval 5; the batch only grows five
        // rounds later.
        #expect(endlessDripTiles(ENDLESS_SLOW_ROUNDS, .regular) == ENDLESS_SMALL_BATCH)
        #expect(endlessDripTiles(ENDLESS_SMALL_BATCH_ROUNDS - 1, .regular) == ENDLESS_SMALL_BATCH)
    }

    @Test("deals sevens forever after")
    func dealsSevensForeverAfter() {
        #expect(endlessDripTiles(ENDLESS_SMALL_BATCH_ROUNDS, .regular) == ENDLESS_BIG_BATCH)
        #expect(endlessDripTiles(20, .regular) == ENDLESS_BIG_BATCH)
        #expect(endlessDripTiles(100, .regular) == ENDLESS_BIG_BATCH)
    }

    @Test("only ever grows")
    func onlyEverGrows() {
        for i in 1...30 {
            #expect(endlessDripTiles(i, .regular) >= endlessDripTiles(i - 1, .regular))
        }
    }
}

@Suite("Modes: endlessDripSeconds, fast") struct ModesEndlessDripSecondsFast {
    @Test("holds fifteen seconds forever — the batch is what grows")
    func holdsFifteenSecondsForever() {
        for i in [0, 1, 7, 8, 55, 56, 500] {
            #expect(endlessDripSeconds(i, .fast) == FAST_DRIP_SECONDS)
            #expect(endlessDripSeconds(i, .fast) == 15)
        }
    }
}

@Suite("Modes: endlessDripTiles, fast") struct ModesEndlessDripTilesFast {
    @Test("deals threes for the first eight rounds")
    func dealsThreesForTheFirstEightRounds() {
        for i in 0..<FAST_BATCH_ROUNDS {
            #expect(endlessDripTiles(i, .fast) == FAST_SMALL_BATCH)
            #expect(endlessDripTiles(i, .fast) == 3)
        }
    }

    @Test("grows the batch by one every eight rounds")
    func growsTheBatchByOneEveryEightRounds() {
        // Two minutes at each size: eight fifteen-second rounds.
        #expect(endlessDripTiles(FAST_BATCH_ROUNDS, .fast) == 4)
        #expect(endlessDripTiles(FAST_BATCH_ROUNDS * 2 - 1, .fast) == 4)
        #expect(endlessDripTiles(FAST_BATCH_ROUNDS * 2, .fast) == 5)
        #expect(endlessDripTiles(FAST_BATCH_ROUNDS * 3, .fast) == 6)
    }

    @Test("tops out at ten and stays there")
    func topsOutAtTenAndStaysThere() {
        // Three grown seven times: round 56 is the first to deal ten.
        let firstMaxRound = FAST_BATCH_ROUNDS * (FAST_MAX_BATCH - FAST_SMALL_BATCH)
        #expect(firstMaxRound == 56)
        #expect(endlessDripTiles(firstMaxRound - 1, .fast) == FAST_MAX_BATCH - 1)
        #expect(endlessDripTiles(firstMaxRound, .fast) == FAST_MAX_BATCH)
        #expect(endlessDripTiles(1000, .fast) == FAST_MAX_BATCH)
    }

    @Test("only ever grows")
    func onlyEverGrows() {
        for i in 1...120 {
            #expect(endlessDripTiles(i, .fast) >= endlessDripTiles(i - 1, .fast))
        }
    }

    @Test("is never gentler than regular on either dial")
    func isNeverGentlerThanRegularOnEitherDial() {
        for i in 0...60 {
            #expect(endlessDripSeconds(i, .fast) < endlessDripSeconds(i, .regular))
        }
    }
}

@Suite("Modes: battleRoundAt") struct ModesBattleRoundAt {
    @Test("splits the game into three-minute rounds, final round forever")
    func splitsTheGameIntoThreeMinuteRounds() {
        #expect(battleRoundAt(seconds: 0) == 1)
        #expect(battleRoundAt(seconds: Double(BATTLE_ROUND_SECONDS - 1)) == 1)
        #expect(battleRoundAt(seconds: Double(BATTLE_ROUND_SECONDS)) == 2)
        #expect(battleRoundAt(seconds: Double(BATTLE_ROUND_SECONDS * 2 - 1)) == 2)
        #expect(battleRoundAt(seconds: Double(BATTLE_ROUND_SECONDS * 2)) == 3)
        #expect(battleRoundAt(seconds: Double(BATTLE_ROUND_SECONDS * 10)) == 3)
    }
}

@Suite("Modes: battleDripTiles") struct ModesBattleDripTiles {
    @Test("brings one, then two, then four tiles a drip")
    func bringsOneThenTwoThenFourTilesADrip() {
        #expect(battleDripTiles(round: 1) == 1)
        #expect(battleDripTiles(round: 2) == 2)
        #expect(battleDripTiles(round: 3) == 4)
    }

    @Test("clamps rounds outside the game")
    func clampsRoundsOutsideTheGame() {
        #expect(battleDripTiles(round: 0) == 1)
        #expect(battleDripTiles(round: 9) == 4)
    }
}

@Suite("Modes: battleDripTilesAt") struct ModesBattleDripTilesAt {
    @Test("sizes each drip by the round it lands in")
    func sizesEachDripByTheRoundItLandsIn() {
        let dripsPerRound = BATTLE_ROUND_SECONDS / BATTLE_DRIP_SECONDS // 9
        // Drips 0..7 land inside round one (at 20s..160s); the drip at 180s
        // opens round two.
        for i in 0..<(dripsPerRound - 1) {
            #expect(battleDripTilesAt(dripIndex: i) == 1)
        }
        #expect(battleDripTilesAt(dripIndex: dripsPerRound - 1) == 2)
        #expect(battleDripTilesAt(dripIndex: dripsPerRound * 2 - 1) == 4)
        #expect(battleDripTilesAt(dripIndex: 100) == 4)
    }
}

@Suite("Modes: battleAttackMultiplier") struct ModesBattleAttackMultiplier {
    @Test("scales rounds at ×1, ×1.5, ×2")
    func scalesRounds() {
        #expect(battleAttackMultiplier(round: 1) == 1)
        #expect(battleAttackMultiplier(round: 2) == 1.5)
        #expect(battleAttackMultiplier(round: 3) == 2)
    }
}

@Suite("Modes: battleAttackTiles") struct ModesBattleAttackTiles {
    @Test("sends nothing for short words")
    func sendsNothingForShortWords() {
        #expect(battleAttackTiles(wordLength: 2, round: 1) == 0)
        #expect(battleAttackTiles(wordLength: 3, round: 1) == 0)
        #expect(battleAttackTiles(wordLength: 3, round: 3) == 0)
    }

    @Test("sends one tile per letter past three in round one")
    func sendsOneTilePerLetterPastThreeInRoundOne() {
        #expect(battleAttackTiles(wordLength: 4, round: 1) == 1)
        #expect(battleAttackTiles(wordLength: 5, round: 1) == 2)
        #expect(battleAttackTiles(wordLength: 6, round: 1) == 3)
        #expect(battleAttackTiles(wordLength: 8, round: 1) == 5)
    }

    @Test("scales up by half in round two")
    func scalesUpByHalfInRoundTwo() {
        #expect(battleAttackTiles(wordLength: 4, round: 2) == 2) // 1 × 1.5 rounds up
        #expect(battleAttackTiles(wordLength: 5, round: 2) == 3)
        #expect(battleAttackTiles(wordLength: 6, round: 2) == 5) // 4.5 rounds up
    }

    @Test("doubles in the final round")
    func doublesInTheFinalRound() {
        #expect(battleAttackTiles(wordLength: 4, round: 3) == 2)
        #expect(battleAttackTiles(wordLength: 5, round: 3) == 4)
        #expect(battleAttackTiles(wordLength: 6, round: 3) == 6)
    }

    @Test("pays only the growth when a word is extended")
    func paysOnlyTheGrowthWhenAWordIsExtended() {
        // HEART (worth 2) stretched to HEARTS (worth 3) earns the difference.
        #expect(battleAttackTiles(wordLength: 6, round: 1, grewFrom: [5]) == 1)
        // CAT was worth nothing, so CATS earns its full value.
        #expect(battleAttackTiles(wordLength: 4, round: 1, grewFrom: [3]) == 1)
        // Adding nothing of value sends nothing.
        #expect(battleAttackTiles(wordLength: 4, round: 1, grewFrom: [4]) == 0)
    }

    @Test("subtracts every word a placement bridges together")
    func subtractsEveryWordAPlacementBridgesTogether() {
        // Two 4-letter words (worth 1 each) joined into a 9-letter word (worth 6).
        #expect(battleAttackTiles(wordLength: 9, round: 1, grewFrom: [4, 4]) == 4)
    }

    @Test("scales the growth by the round multiplier")
    func scalesTheGrowthByTheRoundMultiplier() {
        // One letter of growth, ×1.5 rounds up to 2 — the multiplier applies to
        // the difference, not to each word before subtracting.
        #expect(battleAttackTiles(wordLength: 6, round: 2, grewFrom: [5]) == 2)
        #expect(battleAttackTiles(wordLength: 6, round: 3, grewFrom: [5]) == 2)
    }

    @Test("treats an empty history as a brand-new word")
    func treatsAnEmptyHistoryAsABrandNewWord() {
        #expect(battleAttackTiles(wordLength: 6, round: 1, grewFrom: []) == battleAttackTiles(wordLength: 6, round: 1))
    }
}

@Suite("Modes: battle pile constants") struct ModesBattlePileConstants {
    @Test("caps the pile at twenty-five")
    func capsThePileAtTwentyFive() {
        #expect(BATTLE_PILE_LIMIT == 25)
    }
}

@Suite("Modes: battle constants") struct ModesBattleConstants {
    @Test("seats two to eight players")
    func seatsTwoToEightPlayers() {
        #expect(BATTLE_MIN_PLAYERS == 2)
        #expect(BATTLE_MAX_PLAYERS == 8)
    }
}

@Suite("Modes: splitAttackTiles") struct ModesSplitAttackTiles {
    @Test("hands a lone rival the whole attack")
    func handsALoneRivalTheWholeAttack() {
        #expect(splitAttackTiles(count: 4, targets: 1) == [4])
        #expect(splitAttackTiles(count: 1, targets: 1) == [1])
    }

    @Test("splits evenly when the attack divides")
    func splitsEvenlyWhenTheAttackDivides() {
        #expect(splitAttackTiles(count: 6, targets: 3) == [2, 2, 2])
        #expect(splitAttackTiles(count: 7, targets: 7) == [1, 1, 1, 1, 1, 1, 1])
    }

    @Test("always sums to the attack — a single tile still lands somewhere")
    func alwaysSumsToTheAttack() {
        for count in 0...12 {
            for targets in 1...7 {
                let shares = splitAttackTiles(count: Double(count), targets: targets)
                #expect(shares.count == targets)
                #expect(shares.reduce(0, +) == count)
            }
        }
    }

    @Test("lands the remainder from the given seat, wrapping round")
    func landsTheRemainderFromTheGivenSeatWrappingRound() {
        #expect(splitAttackTiles(count: 5, targets: 3, from: 0) == [2, 2, 1])
        #expect(splitAttackTiles(count: 5, targets: 3, from: 1) == [1, 2, 2])
        #expect(splitAttackTiles(count: 5, targets: 3, from: 2) == [2, 1, 2])
        // The rotation is a courtesy, not a requirement — any offset still sums.
        #expect(splitAttackTiles(count: 5, targets: 3, from: 7) == [1, 2, 2])
        #expect(splitAttackTiles(count: 5, targets: 3, from: -1) == [2, 1, 2])
    }

    @Test("never scales the total up with the size of the room")
    func neverScalesTheTotalUpWithTheSizeOfTheRoom() {
        // Eight players: seven targets take, between them, exactly what one
        // rival would — the room makes each hit smaller, not the game harder.
        let attack = battleAttackTiles(wordLength: 8, round: 3) // a big final-round word
        let shares = splitAttackTiles(count: Double(attack), targets: 7)
        #expect(shares.reduce(0, +) == attack)
        let ceiling = Int((Double(attack) / 7).rounded(.up))
        for share in shares { #expect(share <= ceiling) }
    }

    @Test("shrugs off nonsense")
    func shrugsOffNonsense() {
        #expect(splitAttackTiles(count: 5, targets: 0) == [])
        #expect(splitAttackTiles(count: -3, targets: 4) == [0, 0, 0, 0])
        #expect(splitAttackTiles(count: Double.nan, targets: 4) == [])
    }
}

@Suite("Modes: formatSeconds") struct ModesFormatSeconds {
    @Test("formats whole minutes")
    func formatsWholeMinutes() {
        #expect(formatSeconds(180) == "3:00")
        #expect(formatSeconds(60) == "1:00")
    }

    @Test("pads seconds to two digits")
    func padsSecondsToTwoDigits() {
        #expect(formatSeconds(75) == "1:15")
        #expect(formatSeconds(9) == "0:09")
    }

    @Test("clamps at zero")
    func clampsAtZero() {
        #expect(formatSeconds(0) == "0:00")
        #expect(formatSeconds(-3) == "0:00")
    }
}

// MARK: - Fixture parity

private struct ModesFixture: Decodable {
    struct AttackCase: Decodable {
        let len: Int
        let round: Int
        let grewFrom: [Int]
        let result: Int
    }
    struct SplitCase: Decodable {
        let count: Double
        let targets: Int
        let from: Int
        let shares: [Int]
    }
    struct PacingCase: Decodable {
        let pace: String
        let interval: Int
        let seconds: Int
        let tiles: Int
    }
    struct RoundCase: Decodable {
        let seconds: Double
        let round: Int
    }
    struct DripCase: Decodable {
        let index: Int
        let tiles: Int
    }
    struct InitialSeconds: Decodable {
        let regular: Int
        let fast: Int
    }

    let attack: [AttackCase]
    let split: [SplitCase]
    let pacing: [PacingCase]
    let rounds: [RoundCase]
    let drips: [DripCase]
    let initialSeconds: InitialSeconds
}

@Suite("Modes fixture parity") struct ModesFixtureParity {
    fileprivate let fx: ModesFixture = loadFixture("modes")

    @Test func attackMatchesJsTables() {
        #expect(fx.attack.count > 0)
        for c in fx.attack {
            #expect(
                battleAttackTiles(wordLength: c.len, round: c.round, grewFrom: c.grewFrom) == c.result,
                "len \(c.len) round \(c.round) grewFrom \(c.grewFrom)"
            )
        }
    }

    @Test func splitMatchesJsTables() {
        #expect(fx.split.count > 0)
        for c in fx.split {
            #expect(
                splitAttackTiles(count: c.count, targets: c.targets, from: c.from) == c.shares,
                "count \(c.count) targets \(c.targets) from \(c.from)"
            )
        }
    }

    @Test func pacingMatchesJsTables() throws {
        #expect(fx.pacing.count > 0)
        for c in fx.pacing {
            let pace = try #require(SoloPace(rawValue: c.pace))
            #expect(endlessDripSeconds(c.interval, pace) == c.seconds, "seconds at \(c.pace) interval \(c.interval)")
            #expect(endlessDripTiles(c.interval, pace) == c.tiles, "tiles at \(c.pace) interval \(c.interval)")
        }
    }

    @Test func roundsMatchJsTables() {
        #expect(fx.rounds.count > 0)
        for c in fx.rounds {
            #expect(battleRoundAt(seconds: c.seconds) == c.round, "round at \(c.seconds)s")
        }
    }

    @Test func dripsMatchJsTables() {
        #expect(fx.drips.count > 0)
        for c in fx.drips {
            #expect(battleDripTilesAt(dripIndex: c.index) == c.tiles, "drip \(c.index)")
        }
    }

    @Test func initialSecondsMatchJsTables() {
        #expect(endlessInitialSeconds(.regular) == fx.initialSeconds.regular)
        #expect(endlessInitialSeconds(.fast) == fx.initialSeconds.fast)
    }
}
